
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 4;
  public static final int SUM = 3;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final int PYC = 5;
  public static final int ENTERO = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "SUM",
  "COMA",
  "PYC"
  };
}

