
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 8;
  public static final int ENTERO = 7;
  public static final int EOF = 0;
  public static final int MAS = 9;
  public static final int PYC = 6;
  public static final int EXCL = 3;
  public static final int PARIZQ = 5;
  public static final int error = 1;
  public static final int PARDER = 4;
  public static final int RPRINT = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RPRINT",
  "EXCL",
  "PARDER",
  "PARIZQ",
  "PYC",
  "ENTERO",
  "CADENA",
  "MAS"
  };
}

